# Generated by Django 5.2.8 on 2026-09-23 23:13

from django.db import migrations, models


def normalize_admin_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_superuser=True).update(role="ADMIN", is_staff=True)
    User.objects.filter(role="ADMIN").update(is_staff=True)
    User.objects.exclude(role="ADMIN").filter(is_superuser=False).update(is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_accounts_user_valid_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0002_equipmenttype'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_valid_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('COLABORADOR', 'Colaborador'), ('TECNICO', 'Técnico'), ('ADMIN', 'Administrador')], default='COLABORADOR', max_length=12, verbose_name='perfil'),
        ),
        migrations.RunPython(normalize_admin_roles, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['COLABORADOR', 'TECNICO', 'ADMIN'])), name='accounts_user_valid_role'),
        ),
    ]
