# Generated by Django 5.2.8 on 2026-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_accounts_user_valid_role_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64, unique=True, verbose_name='hash do IP')),
                ('failures', models.PositiveIntegerField(default=0, verbose_name='falhas consecutivas')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='última falha em')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='bloqueado até')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'tentativa de login',
                'verbose_name_plural': 'tentativas de login',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['blocked_until'], name='accounts_lo_blocked_03cd84_idx')],
            },
        ),
    ]
