[project]
name = "chamar"
version = "1.0.0"
description = "API do sistema de chamados de TI"
requires-python = ">=3.12,<3.15"
dependencies = [
  "Django==5.2.8",
  "djangorestframework==3.16.1",
  "djangorestframework-simplejwt==5.5.1",
  "django-filter==25.2",
  "django-cors-headers==4.9.0",
  "drf-spectacular==0.29.0",
  "psycopg[binary]==3.3.2",
  "argon2-cffi==25.1.0",
  "Pillow==12.0.0",
  "gunicorn==23.0.0",
]

[build-system]
requires = ["setuptools==80.9.0"]
build-backend = "setuptools.build_meta"
