# Generated by Django 5.2.8 on 2026-09-23 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ABERTO', 'EM_ATENDIMENTO', 'AGUARDANDO_USUARIO', 'RESOLVIDO', 'FECHADO', 'CANCELADO'])), name='tickets_ticket_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['BAIXA', 'MEDIA', 'ALTA', 'CRITICA'])), name='tickets_ticket_valid_priority'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), ('rating__range', (1, 5)), _connector='OR'), name='tickets_ticket_valid_rating'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['RESOLVIDO', 'FECHADO']), _negated=True), ('resolved_at__isnull', False), _connector='OR'), name='tickets_ticket_resolved_has_date'),
        ),
    ]
