# Generated by Django 5.2.8 on 2026-09-23 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_tickets_ticket_valid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='tickets.ticket'),
        ),
    ]
