import { useEffect, useState } from 'react'
import { api, messageOf, rowsOf, textOf } from '../lib/api'
import { Alert, Empty, Modal, PageHeader, Spinner, StatusBadge } from '../components/Ui'
const configs={sectors:{title:'Setores',singular:'setor',path:'/sectors/',description:'Organize as áreas atendidas pela equipe de TI.',fields:[['nome','Nome do setor','text']]},categories:{title:'Categorias',singular:'categoria',path:'/categories/',description:'Classifique os chamados e facilite a análise.',fields:[['nome','Nome da categoria','text'],['descricao','Descrição','text']]},equipments:{title:'Equipamentos',singular:'equipamento',path:'/equipment-types/',description:'Mantenha os tipos de equipamentos disponíveis nos chamados.',fields:[['nome','Nome / tipo','text'],['descricao','Descrição','text']]}}
export default function CrudPage({type}){const config=configs[type],[data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState({})
 const load=async()=>{setLoading(true);try{const response=await api.get(config.path,{params:{page_size:100}});setData(rowsOf(response.data))}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
 useEffect(()=>{load()},[type])
 const open=(item={})=>{setEditing(item);setForm(Object.fromEntries(config.fields.map(([name])=>[name,item[name]||''])))}
 const submit=async(e)=>{e.preventDefault();setError('');try{const payload={name:form.nome};if(editing?.id)await api.patch(`${config.path}${editing.id}/`,payload);else await api.post(config.path,payload);setNotice(`${config.singular[0].toUpperCase()+config.singular.slice(1)} salvo com sucesso.`);setEditing(null);load()}catch(err){setError(messageOf(err))}}
 const toggle=async(item)=>{try{await api.patch(`${config.path}${item.id}/`,{active:!(item.active??item.ativo??item.ativa)});setNotice('Status atualizado.');load()}catch(err){setError(messageOf(err))}}
 return <><PageHeader eyebrow="Cadastros" title={config.title} description={config.description} actions={<button className="button" onClick={()=>open()}>+ Novo {config.singular}</button>}/><Alert type="success">{notice}</Alert><Alert>{error}</Alert>{loading?<Spinner/>:data.length===0?<Empty title={`Nenhum ${config.singular} cadastrado`} text="Crie o primeiro registro para começar."/>:<section className="table-card"><div className="table-scroll"><table><thead><tr><th>Nome</th><th>Descrição</th><th>Status</th><th>Ações</th></tr></thead><tbody>{data.map(item=><tr key={item.id}><td><strong>{textOf(item)}</strong></td><td>{item.descricao||'—'}</td><td><StatusBadge value={(item.ativo??item.ativa??true)?'Ativo':'Inativo'}/></td><td className="actions-cell"><button className="text-button" onClick={()=>open(item)}>Editar</button><button className="text-button danger-text" onClick={()=>toggle(item)}>{(item.ativo??item.ativa??true)?'Inativar':'Ativar'}</button></td></tr>)}</tbody></table></div></section>}<Modal title={`${editing?.id?'Editar':'Novo'} ${config.singular}`} open={editing!==null} onClose={()=>setEditing(null)}><form onSubmit={submit}>{config.fields.map(([name,label,inputType])=><label key={name}>{label}<input type={inputType} value={form[name]||''} onChange={(e)=>setForm({...form,[name]:e.target.value})} required={name==='nome'}/></label>)}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="button">Salvar</button></div></form></Modal></>}
