import { useEffect, useMemo, useState } from 'react'
import { api, messageOf, rowsOf } from '../lib/api'
import { Alert, Empty, PageHeader, Spinner } from '../components/Ui'
const arrayData = (data) => rowsOf(data)
const labelFor = (item) => item.nome || item.name || item.label || item['sector__name'] || item['category__name'] || item['technician__name'] || item.setor || item.categoria || item.tecnico || item.date || item.data || 'Sem identificação'
const valueFor = (item) => Number(item.total ?? item.quantidade ?? item.count ?? item.value ?? 0)
function BarChart({ data, color = 'green' }) { const max = Math.max(...data.map(valueFor), 1); return <div className="bar-chart">{data.map((item,index)=><div className="bar-row" key={`${labelFor(item)}-${index}`}><span title={labelFor(item)}>{labelFor(item)}</span><div><i className={color} style={{ width: `${(valueFor(item)/max)*100}%` }} /></div><strong>{valueFor(item)}</strong></div>)}</div> }
function Donut({ data }) { const total = data.reduce((sum,item)=>sum+valueFor(item),0) || 1; let offset=0; const colors=['#14783d','#35a562','#87c99e','#d4a72c','#5e7184']; const gradient=data.map((item,index)=>{const start=offset; offset += valueFor(item)/total*100; return `${colors[index%colors.length]} ${start}% ${offset}%`}).join(','); return <div className="donut-layout"><div className="donut" style={{ background: `conic-gradient(${gradient || '#e7ece9 0 100%'})` }}><span><strong>{total}</strong><small>Total</small></span></div><div className="legend">{data.map((item,index)=><p key={`${labelFor(item)}-${index}`}><i style={{background:colors[index%colors.length]}} />{labelFor(item)}<strong>{Math.round(valueFor(item)/total*100)}%</strong></p>)}</div></div> }
function LineChart({ data }) { const width=600,height=220,pad=25,max=Math.max(...data.flatMap((item)=>[Number(item.opened ?? item.abertos ?? 0),Number(item.resolved ?? item.encerrados ?? item.resolvidos ?? 0)]),1); const points=(keys)=>data.map((item,index)=>`${pad+(index*Math.max(1,width-pad*2)/Math.max(data.length-1,1))},${height-pad-(Number(keys.map(key=>item[key]).find(value=>value!==undefined)??0)/max*(height-pad*2))}`).join(' '); return <div className="line-chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Evolução de chamados abertos e encerrados"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} /><polyline points={points(['opened','abertos'])} className="line-open" /><polyline points={points(['resolved','encerrados','resolvidos'])} className="line-closed" /></svg><div className="chart-legend"><span><i className="open" />Abertos</span><span><i className="closed" />Encerrados</span></div></div> }
export default function DashboardPage() {
  const [period,setPeriod]=useState('30d'),[data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all(['/dashboard/summary/','/dashboard/by-sector/','/dashboard/by-technician/','/dashboard/by-category/','/dashboard/timeline/'].map(path=>api.get(path,{params:{periodo:period}}))).then(([summary,sectors,techs,categories,timeline])=>{if(active)setData({summary:summary.data,sectors:arrayData(sectors.data),techs:arrayData(techs.data),categories:arrayData(categories.data),timeline:arrayData(timeline.data)})}).catch(err=>active&&setError(messageOf(err))).finally(()=>active&&setLoading(false));return()=>{active=false}},[period])
  const cards=useMemo(()=>data?[['Total',data.summary.total??data.summary.total_chamados],['Abertos',data.summary.opened??data.summary.abertos],['Em atendimento',data.summary.in_progress??data.summary.em_atendimento??data.summary.em_atendimento_total],['Encerrados',data.summary.closed??data.summary.encerrados??data.summary.resolvidos],['Tempo médio',data.summary.average_resolution_seconds!=null?`${Math.round(data.summary.average_resolution_seconds/3600)}h`:data.summary.tempo_medio_resolucao??data.summary.tempo_medio??'—'],['Taxa de resolução',data.summary.resolution_rate!=null?`${data.summary.resolution_rate}%`:data.summary.taxa_resolucao!=null?`${data.summary.taxa_resolucao}%`:'—']]:[],[data])
  return <><PageHeader eyebrow="Visão operacional" title="Dashboard de suporte" description="Indicadores agregados para apoiar decisões e melhorar o atendimento." actions={<label className="period-select">Período<select value={period} onChange={(e)=>setPeriod(e.target.value)}><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option><option value="90d">Últimos 90 dias</option></select></label>} /><Alert>{error}</Alert>{loading?<Spinner label="Calculando indicadores"/>:data&&<><section className="metric-grid">{cards.map(([label,value],index)=><article key={label} className={index===0?'featured':''}><span>{label}</span><strong>{value??0}</strong><small>{period==='7d'?'nos últimos 7 dias':period==='90d'?'nos últimos 90 dias':'nos últimos 30 dias'}</small></article>)}</section><section className="dashboard-grid"><article className="chart-card"><header><div><h2>Setores com mais problemas</h2><p>Chamados abertos por área</p></div></header>{data.sectors.length?<BarChart data={data.sectors}/>:<Empty text="Sem dados por setor neste período."/>}</article><article className="chart-card"><header><div><h2>Atendimentos por técnico</h2><p>Chamados concluídos</p></div></header>{data.techs.length?<BarChart data={data.techs} color="blue"/>:<Empty text="Sem dados por técnico neste período."/>}</article><article className="chart-card wide"><header><div><h2>Evolução de chamados</h2><p>Abertos x encerrados ao longo do período</p></div></header>{data.timeline.length?<LineChart data={data.timeline}/>:<Empty text="Sem evolução registrada neste período."/>}</article><article className="chart-card"><header><div><h2>Por categoria</h2><p>Distribuição dos chamados</p></div></header>{data.categories.length?<Donut data={data.categories}/>:<Empty text="Sem categorias no período."/>}</article></section></>}</>
}
