import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api, messageOf, rowsOf, textOf } from '../lib/api'
import { Alert, PageHeader } from '../components/Ui'
export default function NewTicketPage() {
  const navigate = useNavigate(), [form, setForm] = useState({ titulo: '', descricao: '', categoria: '', prioridade: 'MEDIA', tipo_equipamento: '' }), [categories, setCategories] = useState([]), [equipments, setEquipments] = useState([]), [files, setFiles] = useState([]), [loading, setLoading] = useState(false), [error, setError] = useState('')
  useEffect(() => { Promise.allSettled([api.get('/categories/', { params: { active: true, page_size: 100 } }), api.get('/equipment-types/', { params: { active: true, page_size: 100 } })]).then(([cats, eqs]) => { setCategories(rowsOf(cats.value?.data)); setEquipments(rowsOf(eqs.value?.data)) }) }, [])
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const chooseFiles = (event) => { const selected = [...event.target.files]; const invalid = selected.find((file) => file.size > 5 * 1024 * 1024 || !['image/png','image/jpeg','application/pdf'].includes(file.type)); if (invalid) { setError(`${invalid.name}: use PNG, JPG ou PDF com até 5 MB.`); return } setFiles(selected); setError('') }
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const payload = { title: form.titulo.trim(), description: form.descricao.trim(), category: Number(form.categoria), urgency_perceived: form.prioridade }; if (form.tipo_equipamento) payload.equipment_type = Number(form.tipo_equipamento); const { data: ticket } = await api.post('/tickets/', payload); for (const file of files) { const body = new FormData(); body.append('file', file); await api.post(`/tickets/${ticket.id}/attachments/`, body) } navigate(`/chamados/${ticket.id}`, { state: { notice: `Chamado ${ticket.number || ''} criado com sucesso.` } }) } catch (err) { setError(messageOf(err)) } finally { setLoading(false) } }
  return <><PageHeader eyebrow="Nova solicitação" title="Como podemos ajudar?" description="Descreva o problema com clareza para agilizar o atendimento." /><div className="form-layout"><form className="panel form-panel" onSubmit={submit}><Alert>{error}</Alert><div className="field-grid"><label className="span-2">Título do chamado<input name="titulo" maxLength="150" value={form.titulo} onChange={change} placeholder="Ex.: Impressora do financeiro não liga" required autoFocus /><small>Seja objetivo e informe o equipamento ou local afetado.</small></label><label>Categoria<select name="categoria" value={form.categoria} onChange={change} required><option value="">Selecione</option>{categories.map((item)=><option key={item.id} value={item.id}>{textOf(item)}</option>)}</select></label><label>Urgência percebida<select name="prioridade" value={form.prioridade} onChange={change}><option value="BAIXA">Baixa — não impede o trabalho</option><option value="MEDIA">Média — impacto parcial</option><option value="ALTA">Alta — trabalho interrompido</option><option value="CRITICA">Crítica — várias pessoas afetadas</option></select></label><label className="span-2">Tipo de equipamento<select name="tipo_equipamento" value={form.tipo_equipamento} onChange={change}><option value="">Não se aplica / outro</option>{equipments.map((item)=><option key={item.id} value={item.id}>{textOf(item.tipo || item)}</option>)}</select></label><label className="span-2">Descrição<textarea name="descricao" rows="7" value={form.descricao} onChange={change} placeholder="Conte o que aconteceu, quando começou e o que você já tentou..." required minLength="10" /><small className="privacy-hint">⚠ Não informe senhas, CPF ou dados pessoais sensíveis.</small></label><label className="span-2 file-drop"><input type="file" multiple accept=".png,.jpg,.jpeg,.pdf" onChange={chooseFiles} /><span>Arraste evidências ou clique para selecionar</span><small>PNG, JPG ou PDF · máximo de 5 MB por arquivo</small>{files.length > 0 && <strong>{files.length} arquivo(s) selecionado(s)</strong>}</label></div><div className="form-actions"><button type="button" className="button secondary" onClick={() => navigate(-1)}>Cancelar</button><button className="button" disabled={loading}>{loading ? 'Criando chamado...' : 'Criar chamado'}</button></div></form><aside className="help-panel"><h2>Antes de enviar</h2><ol><li><span>1</span><div><strong>Confira conexões</strong><p>Cabos, energia e rede resolvem problemas comuns.</p></div></li><li><span>2</span><div><strong>Informe mensagens de erro</strong><p>Copie o texto exato ou anexe uma captura.</p></div></li><li><span>3</span><div><strong>Explique o impacto</strong><p>Diga quantas pessoas ou atividades foram afetadas.</p></div></li></ol><p className="help-note">Sua urgência será avaliada pela equipe técnica e poderá ser ajustada.</p></aside></div></>
}
