import { useEffect, useState } from 'react'
import { api, downloadResponse, idOf, messageOf, rowsOf, textOf } from '../lib/api'
import { useAuth } from '../hooks/useAuth'
import { dateTime, isStaff, isTech } from '../lib/format'
import { Alert, PageHeader } from '../components/Ui'
export default function ProfilePage(){const {user,reloadUser}=useAuth(),[form,setForm]=useState({}),[sectors,setSectors]=useState([]),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[consent,setConsent]=useState(Boolean(user?.consentimento||user?.privacy_consent))
 useEffect(()=>{setForm({nome:user?.nome||user?.name||'',email:user?.email||'',setor:idOf(user?.setor)||''});api.get('/sectors/',{params:{page_size:100}}).then(({data})=>setSectors(rowsOf(data))).catch(()=>{})},[user])
 const save=async(e)=>{e.preventDefault();setLoading(true);setError('');try{await api.patch('/auth/me/',{name:form.nome,sector:form.setor?Number(form.setor):null});await reloadUser();setNotice('Perfil atualizado com sucesso.')}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
 const exportData=async()=>{setLoading(true);try{const {data,headers}=await api.get('/me/data-export/',{responseType:'blob'});const ext=headers['content-type']?.includes('csv')?'csv':'json';downloadResponse(data,`meus-dados-chamar.${ext}`);setNotice('Exportação concluída.')}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
 const saveConsent=async()=>{setLoading(true);try{if(!consent){setError('Marque a declaração de ciência antes de registrar.');return}await api.post('/privacy/consent/',{policy_version:'1.0.0'});setNotice('Ciência da política registrada.')}catch(err){setError(messageOf(err))}finally{setLoading(false)}}
 return <><PageHeader eyebrow="Conta e privacidade" title="Meu perfil" description="Mantenha seus dados corretos e gerencie seus direitos de privacidade."/><Alert type="success">{notice}</Alert><Alert>{error}</Alert><div className="profile-grid"><section className="panel profile-summary"><div className="large-avatar">{(form.nome||'U').charAt(0).toUpperCase()}</div><h2>{form.nome}</h2><p>{form.email}</p><span className="badge">{isStaff(user)?'Administrador':isTech(user)?'Técnico':'Colaborador'}</span><dl><div><dt>Setor</dt><dd>{textOf(user?.setor)}</dd></div><div><dt>Membro desde</dt><dd>{dateTime(user?.date_joined||user?.criado_em)}</dd></div></dl></section><div><section className="panel"><div className="section-title"><h2>Dados pessoais</h2></div><form onSubmit={save} className="field-grid"><label>Nome completo<input value={form.nome||''} onChange={(e)=>setForm({...form,nome:e.target.value})} required/></label><label>E-mail institucional<input type="email" value={form.email||''} onChange={(e)=>setForm({...form,email:e.target.value})} required/></label><label className="span-2">Setor<select value={form.setor||''} onChange={(e)=>setForm({...form,setor:e.target.value})}><option value="">Sem setor</option>{sectors.map(item=><option key={item.id} value={item.id}>{textOf(item)}</option>)}</select></label><div className="form-actions span-2"><button className="button" disabled={loading}>Salvar alterações</button></div></form></section><section className="panel privacy-panel"><div><h2>Privacidade e seus dados</h2><p>Em conformidade com a LGPD, você pode obter uma cópia estruturada dos dados associados à sua conta.</p><button className="button secondary" onClick={exportData} disabled={loading}>↓ Exportar meus dados</button></div><div><h2>Ciência da política</h2><label className="consent"><input type="checkbox" checked={consent} onChange={(e)=>setConsent(e.target.checked)}/><span>Declaro que li a Política de Privacidade, versão 1.0, e estou ciente do tratamento dos meus dados.</span></label><button className="text-button" onClick={saveConsent} disabled={loading}>Registrar preferência</button></div></section></div></div></>}
