import { useEffect, useState } from 'react'
import { Link, useLocation, useParams } from 'react-router-dom'
import { api, downloadResponse, idOf, messageOf, rowsOf, textOf } from '../lib/api'
import { dateTime, isTech, priorityLabel, statusLabel } from '../lib/format'
import { useAuth } from '../hooks/useAuth'
import { Alert, Empty, Modal, PageHeader, Spinner, StatusBadge } from '../components/Ui'
export default function TicketDetailPage() {
  const { id } = useParams(), location = useLocation(), { user } = useAuth(), tech = isTech(user)
  const [ticket, setTicket] = useState(null), [comments, setComments] = useState([]), [attachments, setAttachments] = useState([]), [history, setHistory] = useState([]), [categories, setCategories] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState(location.state?.notice || ''), [comment, setComment] = useState(''), [modal, setModal] = useState(''), [solution, setSolution] = useState(''), [rating, setRating] = useState(5)
  const load = async () => { setLoading(true); setError(''); try { const [detail, com, att, hist, cats] = await Promise.allSettled([api.get(`/tickets/${id}/`), api.get(`/tickets/${id}/comments/`), api.get(`/tickets/${id}/attachments/`), api.get(`/tickets/${id}/history/`), api.get('/categories/', { params: { page_size: 100 } })]); if (detail.status === 'rejected') throw detail.reason; setTicket(detail.value.data); setComments(rowsOf(com.value?.data)); setAttachments(rowsOf(att.value?.data)); setHistory(rowsOf(hist.value?.data)); setCategories(rowsOf(cats.value?.data)) } catch (err) { setError(messageOf(err)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [id])
  const action = async (request, success) => { setBusy(true); setError(''); try { await request(); setNotice(success); setModal(''); await load() } catch (err) { setError(messageOf(err)) } finally { setBusy(false) } }
  const postStatus = (status, message) => action(() => api.post(`/tickets/${id}/status/`, { status }), message)
  const patch = (field, value) => { const apiField = { categoria: 'category', prioridade: 'priority' }[field] || field; return action(() => api.patch(`/tickets/${id}/`, { [apiField]: value }), 'Chamado atualizado.') }
  const sendComment = async (event) => { event.preventDefault(); if (!comment.trim()) return; await action(() => api.post(`/tickets/${id}/comments/`, { text: comment.trim() }), 'Comentário enviado.'); setComment('') }
  const upload = async (event) => { const files = [...event.target.files]; const invalid = files.find((file) => file.size > 5 * 1024 * 1024 || !['image/png','image/jpeg','application/pdf'].includes(file.type)); if (invalid) { setError(`${invalid.name}: formato ou tamanho inválido.`); return } await action(async () => { for (const file of files) { const body = new FormData(); body.append('file', file); await api.post(`/tickets/${id}/attachments/`, body) } }, 'Anexo enviado.') }
  const downloadAttachment = async (item) => { try { const response = await api.get(`/attachments/${item.id}/download/`, { responseType: 'blob' }); downloadResponse(response.data, item.nome || item.original_name || 'anexo') } catch (err) { setError(messageOf(err)) } }
  if (loading && !ticket) return <Spinner label="Carregando chamado" />
  if (!ticket) return <><PageHeader title="Chamado indisponível" /><Alert>{error}</Alert><Empty title="Não foi possível abrir este chamado" text="Ele pode não existir ou você não possui acesso." /></>
  const canCancel = !tech && ticket.status === 'ABERTO', canReopen = !tech && ticket.status === 'RESOLVIDO', canRate = !tech && ['RESOLVIDO','FECHADO'].includes(ticket.status) && !ticket.rating
  return <><PageHeader eyebrow={<Link to="/chamados">← Voltar aos chamados</Link>} title={ticket.titulo} description={`${ticket.numero || `Chamado #${ticket.id}`} · Aberto em ${dateTime(ticket.criado_em)}`} actions={<StatusBadge value={statusLabel(ticket.status)} />} /><Alert type="success">{notice}</Alert><Alert>{error}</Alert>
    <div className="detail-layout"><div className="detail-main"><section className="panel"><div className="section-title"><h2>Descrição do problema</h2></div><p className="preserve">{ticket.descricao}</p>{ticket.solucao && <div className="solution"><strong>Solução aplicada</strong><p className="preserve">{ticket.solucao}</p></div>}</section>
      <section className="panel"><div className="section-title"><h2>Conversa</h2><span>{comments.length} comentário(s)</span></div>{comments.length === 0 ? <p className="muted">Ainda não há comentários.</p> : <div className="comments">{comments.map((item)=><article key={item.id}><span className="comment-avatar">{textOf(item.autor, 'U').charAt(0)}</span><div><header><strong>{textOf(item.autor, 'Usuário')}</strong><time>{dateTime(item.criado_em)}</time></header><p className="preserve">{item.texto || item.text || item.comentario}</p></div></article>)}</div>}<form className="comment-form" onSubmit={sendComment}><label><span className="sr-only">Novo comentário</span><textarea rows="3" value={comment} onChange={(e)=>setComment(e.target.value)} placeholder="Escreva uma atualização ou dúvida..." required /></label><button className="button" disabled={busy}>Enviar comentário</button></form></section>
      <section className="panel"><div className="section-title"><h2>Anexos</h2><label className="button small secondary">+ Adicionar<input className="sr-only" type="file" accept=".png,.jpg,.jpeg,.pdf" multiple onChange={upload} /></label></div>{attachments.length === 0 ? <p className="muted">Nenhum arquivo anexado.</p> : <div className="attachment-list">{attachments.map((item)=><button type="button" key={item.id} onClick={()=>downloadAttachment(item)}><span>▧</span><div><strong>{item.nome || item.filename || 'Anexo'}</strong><small>{dateTime(item.criado_em)}</small></div><b>↓</b></button>)}</div>}</section>
      <section className="panel"><div className="section-title"><h2>Histórico</h2></div><div className="timeline">{history.length === 0 ? <p className="muted">Nenhuma alteração registrada.</p> : history.map((item)=><article key={item.id}><span /><div><strong>{item.descricao || `${statusLabel(item.status_anterior)} → ${statusLabel(item.status_novo)}`}</strong><p>{textOf(item.alterado_por, 'Sistema')} · {dateTime(item.criado_em)}</p></div></article>)}</div></section></div>
      <aside className="detail-side"><section className="panel info-list"><h2>Informações</h2><dl><div><dt>Solicitante</dt><dd>{textOf(ticket.solicitante)}</dd></div><div><dt>Setor</dt><dd>{textOf(ticket.setor)}</dd></div><div><dt>Categoria</dt><dd>{tech ? <select aria-label="Alterar categoria" value={idOf(ticket.categoria) || ''} onChange={(e)=>patch('categoria', Number(e.target.value))}>{categories.map((item)=><option key={item.id} value={item.id}>{textOf(item)}</option>)}</select> : textOf(ticket.categoria)}</dd></div><div><dt>Prioridade</dt><dd>{tech ? <select aria-label="Alterar prioridade" value={ticket.prioridade} onChange={(e)=>patch('prioridade', e.target.value)}>{['BAIXA','MEDIA','ALTA','CRITICA'].map((value)=><option key={value} value={value}>{priorityLabel(value)}</option>)}</select> : priorityLabel(ticket.prioridade)}</dd></div><div><dt>Responsável</dt><dd>{textOf(ticket.tecnico, 'Não atribuído')}</dd></div><div><dt>Última atualização</dt><dd>{dateTime(ticket.atualizado_em)}</dd></div></dl></section>
      <section className="panel action-panel"><h2>Ações</h2>{tech && !ticket.tecnico && <button className="button wide" disabled={busy} onClick={()=>action(()=>api.post(`/tickets/${id}/assign/`), 'Chamado assumido com sucesso.')}>Assumir chamado</button>}{tech && ticket.status === 'ABERTO' && <button className="button secondary wide" onClick={()=>postStatus('EM_ATENDIMENTO','Atendimento iniciado.')}>Iniciar atendimento</button>}{tech && ticket.status === 'EM_ATENDIMENTO' && <button className="button secondary wide" onClick={()=>postStatus('AGUARDANDO_USUARIO','Aguardando retorno do usuário.')}>Aguardar usuário</button>}{tech && ticket.status === 'AGUARDANDO_USUARIO' && <button className="button secondary wide" onClick={()=>postStatus('EM_ATENDIMENTO','Atendimento retomado.')}>Retomar atendimento</button>}{tech && ['EM_ATENDIMENTO','AGUARDANDO_USUARIO'].includes(ticket.status) && <button className="button wide" onClick={()=>setModal('resolve')}>Resolver chamado</button>}{canCancel && <button className="button danger wide" onClick={()=>postStatus('CANCELADO','Chamado cancelado.')}>Cancelar chamado</button>}{canReopen && <button className="button secondary wide" onClick={()=>postStatus('EM_ATENDIMENTO','Chamado reaberto.')}>Reabrir chamado</button>}{canRate && <button className="button wide" onClick={()=>setModal('rate')}>Avaliar atendimento</button>}</section></aside></div>
    <Modal title="Resolver chamado" open={modal==='resolve'} onClose={()=>setModal('')}><form onSubmit={(e)=>{e.preventDefault(); action(()=>api.post(`/tickets/${id}/resolve/`, { solution }), 'Chamado resolvido com sucesso.')}}><label>Solução aplicada<textarea rows="5" value={solution} onChange={(e)=>setSolution(e.target.value)} required minLength="10" placeholder="Descreva o diagnóstico e a solução..." /></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setModal('')}>Cancelar</button><button className="button" disabled={busy}>Confirmar solução</button></div></form></Modal>
    <Modal title="Avaliar atendimento" open={modal==='rate'} onClose={()=>setModal('')}><form onSubmit={(e)=>{e.preventDefault(); action(()=>api.post(`/tickets/${id}/rate/`, { rating: Number(rating) }), 'Obrigado pela sua avaliação!')}}><label>Como foi o atendimento?<select value={rating} onChange={(e)=>setRating(e.target.value)}>{[5,4,3,2,1].map((value)=><option key={value} value={value}>{'★'.repeat(value)} — {value}</option>)}</select></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setModal('')}>Cancelar</button><button className="button">Enviar avaliação</button></div></form></Modal></>
}
