import { useEffect, useState } from 'react'
import { api, idOf, messageOf, rowsOf, textOf } from '../lib/api'
import { Alert, Empty, Modal, PageHeader, Spinner, StatusBadge } from '../components/Ui'
export default function UsersPage(){const [users,setUsers]=useState([]),[sectors,setSectors]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(null),[form,setForm]=useState({})
 const load=async()=>{setLoading(true);try{const [u,s]=await Promise.all([api.get('/users/',{params:{page_size:100}}),api.get('/sectors/',{params:{page_size:100}})]);setUsers(rowsOf(u.data));setSectors(rowsOf(s.data))}catch(err){setError(messageOf(err))}finally{setLoading(false)}};useEffect(()=>{load()},[])
 const open=(user={})=>{setEditing(user);setForm({nome:user.nome||user.name||'',email:user.email||'',perfil:user.perfil||'COLABORADOR',setor:idOf(user.setor)||'',ativo:user.ativo??user.is_active??true,password:''})}
 const submit=async(e)=>{e.preventDefault();try{const payload={name:form.nome,email:form.email,role:form.perfil,sector:form.setor?Number(form.setor):null,is_active:form.ativo};if(!editing?.id)payload.password=form.password;if(editing?.id)await api.patch(`/users/${editing.id}/`,payload);else await api.post('/users/',payload);setEditing(null);setNotice('Usuário salvo com sucesso.');load()}catch(err){setError(messageOf(err))}}
 const anonymize=async(user)=>{if(!window.confirm(`Anonimizar ${textOf(user)}? Esta ação não pode ser desfeita.`))return;try{await api.post(`/users/${user.id}/anonymize/`);setNotice('Usuário anonimizado.');load()}catch(err){setError(messageOf(err))}}
 return <><PageHeader eyebrow="Administração" title="Usuários" description="Gerencie acessos, perfis e conformidade dos usuários." actions={<button className="button" onClick={()=>open()}>+ Novo usuário</button>}/><Alert type="success">{notice}</Alert><Alert>{error}</Alert>{loading?<Spinner/>:users.length===0?<Empty title="Nenhum usuário"/>:<section className="table-card"><div className="table-scroll"><table><thead><tr><th>Usuário</th><th>Setor</th><th>Perfil</th><th>Status</th><th>Ações</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><strong>{textOf(user)}</strong><small>{user.email}</small></td><td>{textOf(user.setor)}</td><td>{user.is_staff?'Administrador':user.perfil}</td><td><StatusBadge value={(user.ativo??user.is_active)?'Ativo':'Inativo'}/></td><td className="actions-cell"><button className="text-button" onClick={()=>open(user)}>Editar</button><button className="text-button danger-text" onClick={()=>anonymize(user)}>Anonimizar</button></td></tr>)}</tbody></table></div></section>}<Modal title={`${editing?.id?'Editar':'Novo'} usuário`} open={editing!==null} onClose={()=>setEditing(null)}><form onSubmit={submit}><label>Nome<input value={form.nome||''} onChange={(e)=>setForm({...form,nome:e.target.value})} required/></label><label>E-mail<input type="email" value={form.email||''} onChange={(e)=>setForm({...form,email:e.target.value})} required/></label><label>Perfil<select value={form.perfil||''} onChange={(e)=>setForm({...form,perfil:e.target.value})}><option value="COLABORADOR">Colaborador</option><option value="TECNICO">Técnico</option><option value="ADMIN">Administrador</option></select></label><label>Setor<select value={form.setor||''} onChange={(e)=>setForm({...form,setor:e.target.value})}><option value="">Sem setor</option>{sectors.map(item=><option key={item.id} value={item.id}>{textOf(item)}</option>)}</select></label>{!editing?.id&&<label>Senha provisória<input type="password" minLength="10" value={form.password||''} onChange={(e)=>setForm({...form,password:e.target.value})} required/></label>}<label className="check"><input type="checkbox" checked={Boolean(form.ativo)} onChange={(e)=>setForm({...form,ativo:e.target.checked})}/> Usuário ativo</label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="button">Salvar</button></div></form></Modal></>}
